import withLanguage from "../../../../components/LanguageContext";
import texts from "../../texts";

import React from "react";
import PlainNavBar from "../PlainNavBar";
import MyProfileButton from "./MyProfileButton";
import Log from "../../../../components/Log";

/**
 * TODO index.js:1 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>.
 *      Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
 *
 * SOLUTION: https://stackoverflow.com/questions/41716528/react-tr-cannot-appear-as-a-child-of-td-see-comment-td-tr
 */

/**
 * Class that represents the navigation bar of the marketplace screen.
 * It has the default go back button and a button to go to the profile section.
 */
class MarketplaceNavBar extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        const language = this.props.language;
        const txt = texts[language].marketplaceScreen;

        return (

            <div className="w-100 mx-auto family-color">
                <table className="w-100 mx-auto">
                    <tr>
                        <td className="w-80">
                            <PlainNavBar title={txt.title}/>
                        </td>

                        <td className="w-10">
                           <MyProfileButton />
                        </td>

                    </tr>
                </table>
            </div>

        );
    }

}

export default withLanguage(MarketplaceNavBar);
