import withLanguage from "../../../components/LanguageContext";

import React from "react";
import PropTypes from "prop-types";
import Log from "../../../components/Log";

import texts from "../texts";


class LargeTextInput extends React.Component {

    constructor(props) {
        super(props);

        this.handleTextChange = this.handleTextChange.bind(this);
    }

    render() {
        return (
            <div className="text-center">
                <h4>{this.props.description}</h4>
                <textarea onChange={this.handleTextChange}
                          placeholder={this.props.placeholder}
                          value={this.props.text}
                          className="descPosting">
                </textarea>
            </div>
        );
    }

    /**
     * Called when the input text of this component is changed.
     * The argument is an event generated by the input element.
     * @param e {InputEvent}
     * @return {Promise<void>}
     */
    async handleTextChange(e) {
        this.props.textChangeHandler(e.target.value);
    }
}

LargeTextInput.defaultProps = {
    text: "",
    description: "",
    textChangeHandler: null
}

LargeTextInput.propTypes = {
    /**
     * Text to display in the input zone
     */
    text: PropTypes.string,

    /**
     * Text shown when there is no input
     */
    placeholder: PropTypes.string,

    /**
     * Description that is showed alongside the input zone
     */
    description: PropTypes.string,

    /**
     * Function that handles what happens when the text is changed
     */
    textChangeHandler: PropTypes.func.isRequired,

    /**
     * Passed by the withLanguage HOC, used to determine which texts to display.
     */
    language: PropTypes.string
}

export default withLanguage(LargeTextInput);
